export default {
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1db64337": [() => import(/* webpackChunkName: "1db64337" */ "@site/docs/overview.md"), "@site/docs/overview.md", require.resolveWeak("@site/docs/overview.md")],
  "22dd74f7": [() => import(/* webpackChunkName: "22dd74f7" */ "@generated/docusaurus-plugin-content-docs/default/p/index-466.json"), "@generated/docusaurus-plugin-content-docs/default/p/index-466.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/index-466.json")],
  "4f9e219b": [() => import(/* webpackChunkName: "4f9e219b" */ "@site/docs/endpoints/device.md"), "@site/docs/endpoints/device.md", require.resolveWeak("@site/docs/endpoints/device.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "625b1ed7": [() => import(/* webpackChunkName: "625b1ed7" */ "@site/docs/authentication.md"), "@site/docs/authentication.md", require.resolveWeak("@site/docs/authentication.md")],
  "69756ce7": [() => import(/* webpackChunkName: "69756ce7" */ "@site/docs/migration-woowa.md"), "@site/docs/migration-woowa.md", require.resolveWeak("@site/docs/migration-woowa.md")],
  "88c467d0": [() => import(/* webpackChunkName: "88c467d0" */ "@site/docs/payloads.md"), "@site/docs/payloads.md", require.resolveWeak("@site/docs/payloads.md")],
  "97b55cc3": [() => import(/* webpackChunkName: "97b55cc3" */ "@site/docs/endpoints/messages.md"), "@site/docs/endpoints/messages.md", require.resolveWeak("@site/docs/endpoints/messages.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "b4cdffe0": [() => import(/* webpackChunkName: "b4cdffe0" */ "@site/docs/endpoints/webhook.md"), "@site/docs/endpoints/webhook.md", require.resolveWeak("@site/docs/endpoints/webhook.md")],
  "dd611e1c": [() => import(/* webpackChunkName: "dd611e1c" */ "@site/docs/endpoints/schedules.md"), "@site/docs/endpoints/schedules.md", require.resolveWeak("@site/docs/endpoints/schedules.md")],
  "ebaeab7c": [() => import(/* webpackChunkName: "ebaeab7c" */ "@site/docs/endpoints/groups.md"), "@site/docs/endpoints/groups.md", require.resolveWeak("@site/docs/endpoints/groups.md")],
  "fd51828f": [() => import(/* webpackChunkName: "fd51828f" */ "@site/docs/error-codes.md"), "@site/docs/error-codes.md", require.resolveWeak("@site/docs/error-codes.md")],};
