export type ConversationListFilter = "UNASSIGNED" | "MY" | "ALL";
export type ConversationStatusFilter = "OPEN" | "CLOSED";

export type ConversationItem = {
  id: string;
  orgId: string;
  customerId: string;
  customerPhoneE164: string;
  customerDisplayName: string | null;
  customerAvatarUrl: string | null;
  customerLeadStatus: string | null;
  crmPipelineId: string | null;
  crmPipelineName: string | null;
  crmStageId: string | null;
  crmStageName: string | null;
  lastMessagePreview: string | null;
  lastMessageType: string | null;
  lastMessageDirection: "INBOUND" | "OUTBOUND" | null;
  source: string | null;
  sourceCampaign: string | null;
  sourceAdset: string | null;
  sourceAd: string | null;
  sourcePlatform: string | null;
  sourceMedium: string | null;
  status: "OPEN" | "CLOSED";
  assignedToMemberId: string | null;
  assignedToMemberName: string | null;
  lastMessageSenderName: string | null;
  groupParticipants: string[];
  shortlinkId: string | null;
  waChatJid: string | null;
  lastMessageAt: string | null;
  unreadCount: number;
  updatedAt: string;
};
