export type MessageItem = {
  id: string;
  waMessageId: string | null;
  replyToMessageId: string | null;
  replyToWaMessageId: string | null;
  replyPreviewText: string | null;
  replyPreviewSenderName: string | null;
  senderWaJid: string | null;
  senderPhoneE164: string | null;
  senderDisplayName: string | null;
  direction: "INBOUND" | "OUTBOUND";
  type: "TEXT" | "IMAGE" | "VIDEO" | "AUDIO" | "DOCUMENT" | "TEMPLATE" | "SYSTEM";
  text: string | null;
  mediaId: string | null;
  mediaUrl: string | null;
  mimeType: string | null;
  fileName: string | null;
  fileSize: number | null;
  templateName: string | null;
  templateCategory: "MARKETING" | "UTILITY" | "AUTHENTICATION" | "SERVICE" | null;
  templateLanguageCode: string | null;
  isAutomated: boolean;
  sendStatus: "PENDING" | "SENT" | "FAILED" | null;
  deliveryStatus: "SENT" | "DELIVERED" | "READ" | null;
  sendError: string | null;
  retryable: boolean;
  sendAttemptCount: number;
  deliveredAt: string | null;
  readAt: string | null;
  createdAt: string;
};
